version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_1_network
    volumes:
      - gis_1_static:/data/static/
      - gis_1_media:/data/media/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_1_django:3
    networks:
      - gis_1_network
    volumes:
      - gis_1_static:/home/gis_1ban/staticfiles/
      - gis_1_media:/home/gis_1ban/media/

networks:
  gis_1_network:

volumes:
  gis_1_static:
  gis_1_media: